// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_hAzdKLduK1WiAe8WbHg9z9UtggNCkMQ',
    appId: '1:755447915710:web:43f9d612583f5e1a29eaef',
    messagingSenderId: '755447915710',
    projectId: 'bgfgnotifications',
    authDomain: 'bgfgnotifications.firebaseapp.com',
    storageBucket: 'bgfgnotifications.appspot.com',
    measurementId: 'G-1HJP7T340Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHV__wy7wxUyUtzMfnpaW5Y23873pBSEc',
    appId: '1:755447915710:android:a8e29c04f441a3c429eaef',
    messagingSenderId: '755447915710',
    projectId: 'bgfgnotifications',
    storageBucket: 'bgfgnotifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03NnQuvvtBFeDJP7RBcmxjlggLWUPVIA',
    appId: '1:755447915710:ios:2d0b519eab92318d29eaef',
    messagingSenderId: '755447915710',
    projectId: 'bgfgnotifications',
    storageBucket: 'bgfgnotifications.appspot.com',
    iosBundleId: 'com.example.bgFgNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB03NnQuvvtBFeDJP7RBcmxjlggLWUPVIA',
    appId: '1:755447915710:ios:e3128249ee3a91a329eaef',
    messagingSenderId: '755447915710',
    projectId: 'bgfgnotifications',
    storageBucket: 'bgfgnotifications.appspot.com',
    iosBundleId: 'com.example.bgFgNotifications.RunnerTests',
  );
}
